--- #YAML:1.0
name:                WWW-Mechanize-GZip
version:             0.10
abstract:            tries to fetch webpages with gzip-compression
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Compress::Zlib:                0
    Test::More:                    0
    WWW::Mechanize:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Peter Giessner <cardb@planet-elektronik.de>
